name: Assess code format

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

      - name: Lint with ruff
        run: |
          ruff src/

      - name: Test with pytest
        run: |
          pytest tests/
